### ISSUE TITLE
Can't install module

### ISSUE THREAD

**Issue by Drag0nF** [OtherwiseJunk/FoundryVTT-Collegiate-Tracking-Sheet#1]
This module looks perfect for my game! thanks for making it, I just wish it would let you download it lol.

Whenever you try to download it, it gets stuck at 100% and pulls this error. 

![image](https://github.com/OtherwiseJunk/FoundryVTT-Collegiate-Tracking-Sheet/assets/79474032/fb11cae6-d0a2-47dd-8b25-c42703168005)

**Comment by OtherwiseJunk** [comment]
@Drag0nF should be fixed with the v1.0.1 release.

![image](https://github.com/OtherwiseJunk/FoundryVTT-Collegiate-Tracking-Sheet/assets/4574230/36c227e6-2c4c-4ad1-a1f6-3daa0e272f95)


Just confirmed I was able to add a sheet in my production server and configure it.

There's a handful of translation strings I have miss-mapped and the year value isn't persisting/showing on the sheet but I should be able to fix those this evening with a 1.0.2 release, 1.0.1 should be enough to get you going though.

Let me know if you notice any issues or have any other suggestions please :D
