### ISSUE TITLE
Sheets can't be renamed

### ISSUE THREAD

**Issue by Drag0nF** [OtherwiseJunk/FoundryVTT-Collegiate-Tracking-Sheet#2]
Once you make a sheet, you can't then rename the sheet itself. The other fields work well, though I wish there was a button for adding a reroll/dice not just using them, and also a field to input the exam date.

**Comment by OtherwiseJunk** [comment]
I can map the field currently used for Student Name in the header to the sheet name if that works for this; IDK if it makes sense to have two "name" like fields but if you think that would be preferable I can go that route.

I can also look at buttons for actually rolling these dice, though it might start looking a bit crowded 🤔 I'll have to check.

Field for exam date should be fine; I had planned on adding a "Year" value, idk if that covers what you need or if you'd also want a "Date Taken" field.

**Comment by Drag0nF** [comment]
Yeah, I see your point on the clutter, but I do think aswell that the rule is that the student die used reset after a long rest, so having the ability to click a button to clear the used die would be great. Just at the bottom of the page, a button that would reset the used die for all the classes at once.
 
 On the topic of the name itself, I wouldn't map the name of the file to the student name, as it would be a bit crowded, I agree, but what could be done is in the top right, add a cog icon like they have in regular character sheets, when clicked, it pulls up a dialog box like the class editing does, and have the field there be able to change the name of the sheet. 
 
A field that literally just says 'Date' would be ideal, so that way people can use it for a variety of means, so they could put the year number in, or an actual date. Have it so that it expands row though like the name does, so people could fit a full date in. My dream would be that this could be linked to simple calendar, where it would search for a note or whatever with a name you specify and tell you how many days you are away from it, and also if you hovered over the time (e.g. 2 days away) it would then give you the full date of when it was/is
 
 One last suggestion I'd have is one thats more complex, so not 100% that it would work, but the ability to 'link' a character sheet to a tracking sheet, so when it rolls a long rest, it would also refresh the dice usage on the tracking sheet. This could be linked by just having an extra field in that cog option I mentioned earlier where you could input the actor id, but that's just an idea, I'm still a fledgling js coder so not 100% how difficult that would be in foundry.  
 
Again though, this module is super useful already, I'm only giving suggestions that would improve it in my opinion, you don't have to listen to me. Though the renaming thing is a big issue.

**Comment by OtherwiseJunk** [comment]
Short term I'm going to add a fourth field at the top for the sheet name, eventually I'll move to a button on the header but it's a bit more involved because I have to manually intercept the window creation, but long term I'll move towards something like that.

Looking at the other suggestions but I probably won't get an update out this evening

![image](https://github.com/OtherwiseJunk/FoundryVTT-Collegiate-Tracking-Sheet/assets/4574230/69c49a15-f08b-4725-93b5-00dbcf1b2dbd)

**Comment by OtherwiseJunk** [comment]
So I was reading the rules again just to make sure my understanding is right, and the wording makes me think the Exam student dice don't come back on a long rest, only the extracurricular dice. 

Otherwise the number of student dice you get from the Exam wouldn't really matter; you can only use one Student Dice a day anyway and you can select from either of the applicable abilities from the exam both times from what I can tell, so having one or two dice wouldn't otherwise matter.

I'd be happy to include the long rest button for resetting the check marks on the extracurriculars if it would be helpful though.

**Comment by OtherwiseJunk** [comment]
Ok I think 1.0.2 should get you most of what you wanted.

![image](https://github.com/OtherwiseJunk/FoundryVTT-Collegiate-Tracking-Sheet/assets/4574230/6763ec03-8eb1-4b36-b5c9-82ee8bfb2fd7)


I want to look into if it's possible to hook into the long rest trigger other sheets give off but I'm not positive it would be 😅 but we'll see!

**Comment by OtherwiseJunk** [comment]
1.0.3 will have a fix for that other new string I broke like a dork 😎

**Comment by Drag0nF** [comment]
this looks awesome! thanks for taking my suggestions!
